release scripts

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -1,1 +1,74 @@
+# Release to PyPi on tag creation
+name: Publish to Test PyPI
 
+# Notes - do we need to use build matrix test strategy - e.g. can this run if the other fails
+# Set as manual only for now due to the above.
+on: workflow_dispatch
+# on:
+#   push:
+#     tags:
+#       - 'v*.*.*'
+
+jobs:
+  test_pypi_release:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+
+    # Install package and dependencies
+    - name: Install
+      run: |
+        # Upgrade pip
+        python -m pip install --upgrade pip
+        # Install the package
+        pip install --force-reinstall -e .
+        # Development dependencies
+        pip install --force-reinstall -r requirements.txt
+        # Install additional GitHub actions build dependencies
+        pip install setuptools wheel twine
+    
+    # TEST: ref. https://github.community/t/how-to-get-just-the-tag-name/16241/11
+    - name: Source Version
+      id: source_version
+      run: |
+        ver=`cat osducli/__init__.py | grep __VERSION__ | sed s/' '//g | sed s/'__VERSION__='// |  sed s/\"//g`
+        echo $ver > $BUILD_STAGINGDIRECTORY/version
+    # TO DO: - compare source and tag version
+    - name: Branch name
+      id: branch_name
+      run: |
+        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
+        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
+        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}    
+    - name: Build base image
+      run: |
+        echo $SOURCE_NAME
+        echo $SOURCE_BRANCH
+        echo $SOURCE_TAG
+      env:
+        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
+        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
+        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
+
+    - name: Check if tag version matches project version
+      run: |
+        TAG=$(git describe HEAD --tags --abbrev=0)
+        echo $TAG
+        echo $PROJECT_VERSION
+        if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi
+
+    # Upload to TestPyPI
+    - name: Build and Upload to TestPyPI
+      run: |
+        python setup.py sdist bdist_wheel
+        python -m twine upload dist/*
+      env:
+        TWINE_USERNAME: __token__
+        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_KEY }}
+        TWINE_REPOSITORY: testpypi
